kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx8g
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.enableIntransitiveMetadataConfiguration=true
kotlin.incremental.native=true
kotlin.native.disableCompilerDaemon=false
kotlin.native.linkerOptions=-dead_strip
kotlin.native.cocoapods.generate.wrapper=true
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=false
org.gradle.configuration-cache=true
